---
- hosts: all
  vars_files:
    - ../vars/main.yml
  name: Creates Subversion directory
  roles:
    - { role: ansible-role-svn }
    - { role: ansible-role-jenkins }
    - { role: distkloc.gitbucket }
